parameters:
    wealthbot_docusign.connection:
        username:       "%docusign_username%"
        password:       "%docusign_password%"
        integratorKey:  "%docusign_integrator_key%"
        brand_id:       "%docusign_brand_id%"
        #account_id:     350278
    wealthbot_docusign.templates:
        personal_account:               "%docusign_personal_account%"
        ira_account:                    "%docusign_ira_account%"
        electronic_funds_transfer_form: "%docusign_electronic_funds_transfer_form%"
        account_transfer_form:          "%docusign_account_transfer_form%"
        check_request:                  "%docusign_check_request%"
        wire_instructions:              "%docusign_wire_instructions%"
        ira_distribution_form:          "%docusign_ira_distribution_form%"
        beneficiary_designation_form:   "%docusign_beneficiary_designation_form%"

    wealthbot_docusign.api_client.class: App\Docusign\DocusignSessionPersistence
    wealthbot_docusign.account_docusign.class: App\Entity\ClientAccountDocusign
    wealthbot_docusign.account_signature.class: App\Entity\DocumentSignature
    wealthbot_docusign.account_owner_signature.class: App\Entity\DocumentOwnerSignature

services:
    wealthbot_docusign.account_docusign.manager:
        class: App\Manager\AccountDocusignManager
        arguments: ["@doctrine.orm.entity_manager", "%wealthbot_docusign.account_docusign.class%"]
        public: true
    wealthbot_docusign.document_signature.manager:
        class: App\Manager\DocumentSignatureManager
        arguments: ["@doctrine.orm.entity_manager", "%wealthbot_docusign.account_signature.class%", "%wealthbot_docusign.account_owner_signature.class%"]
        public: true

    wealthbot_docusign.api_client:
        class: "%wealthbot_docusign.api_client.class%"
        arguments: ["%wealthbot_docusign.connection%", "@session"]
        public: true
    wealthbot_docusign.electronic_signature_service:
        class: App\Service\ElectronicSignatureService
        arguments: ["@wealthbot_docusign.api_client", "@wealthbot_docusign.document_signature.manager", "@wealthbot_docusign.account_docusign.manager", "%wealthbot_docusign.templates%"]
        public: true
    wealthbot_user.twig.signature_extension:
        class: App\Twig\SignatureTwigExtension
        arguments: ["@wealthbot_docusign.document_signature.manager"]
        tags:
            - { name: twig.extension }
        public: true