rx_user_homepage:
    path:  /
    defaults: { _controller: App\Controller\User\DefaultController:index }

login:
    path:  /login
    defaults: { _controller: App\Controller\User\SecurityController:login }

logout:
    path:  /logout
    defaults: { _controller: App\Controller\User\SecurityController:logout }
check:
    path:  /check
    defaults: { _controller: App\Controller\User\SecurityController:check }

rx_after_login:
    path:  /after-login
    defaults: { _controller: App\Controller\User\RolesController:afterLogin }


rx_ria_register:
    path: /ria/registration
    defaults: { _controller: App\Controller\User\RiaController:registration }

rx_client_registration:
    path: /client/registration/{ria_id}
    defaults: { _controller: App\Controller\User\ClientController:registration }

rx_client_step2:
    path: /client/step2
    defaults: { _controller: App\Controller\User\ClientController:step2 }

rx_client_step3:
    path: /client/step3
    defaults: { _controller: App\Controller\User\ClientController:step3 }

rx_client_create_investment_account:
    path: /client/step3/create
    defaults: { _controller: App\Controller\User\ClientController:createInvestmentAccount }

rx_client_add_retirement_form:
    path:  /client/add-retirement-form
    defaults: { _controller: App\Controller\User\ClientController:addRetirementAccountForm }

rx_client_create_retirement_account:
    path: /client/step3/create-retirement
    defaults: { _controller: App\Controller\User\ClientController:createRetirementAccount }

rx_client_create_retirement_fund:
    path: /client/step3/create-retirement-fund
    defaults: { _controller: App\Controller\User\ClientController:createRetirementFund }

rx_client_finish_registration:
    path: /client/finish-registration
    defaults: { _controller: App\Controller\User\ClientController:finishRegistration }

rx_search_ria:
    path:  /search-ria
    defaults: { _controller: App\Controller\User\DefaultController:searchRia }

rx_reset_user_password:
    path: /user/{user_id}/reset-password
    defaults: { _controller: App\Controller\User\ChangePasswordController:resetPassword }
    requirements:
        user_id: \d+

rx_user_switch_to_admin:
    path: /user/switch-to-admin
    defaults: { _controller: App\Controller\User\DefaultController:switchToAdmin }

rx_complete_transfer_custodian:
    path: /complete-custodian
    defaults: { _controller: App\Controller\User\DefaultController:completeTransferCustodian }

rx_file_download:
    path: /file/logo/ria/{ria_id}
    defaults: { _controller: App\Controller\User\FilesController:logo }

rx_download_document:
    path: /uploads/documents/{filename}/{originalName}
    defaults: { _controller: App\Controller\User\FilesController:documents, originalName: null }

rx_download_trade_file:
    path: /file/trade-file/{filename}/{originalName}
    defaults: { _controller: App\Controller\User\FilesController:tradeFile, originalName: null }

rx_security_reset_password:
    path:  /forgot-password
    defaults: { _controller: App\Controller\User\SecurityController:resetPassword}