App\Entity\AccountGroup:
  type: entity
  table: client_account_groups
  repositoryClass: App\Repository\AccountGroupRepository
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    name:
      type: string(255)
      nullable: false
  oneToMany:
    groupTypes:
      targetEntity:  App\Entity\AccountGroupType
      mappedBy: group
      cascade: ['persist']
  lifecycleCallbacks: {  }