App\Entity\AccountOutsideFund:
  type: entity
  table: account_outside_funds
  repositoryClass: App\Repository\AccountOutsideFundRepository
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    account_id:
      type: integer
      nullable: true
    security_assignment_id:
      type: integer
      nullable: false
    is_preferred:
      type: boolean
      nullable: false
  uniqueConstraints:
    account_outside_fund:
      columns:
        - account_id
        - security_assignment_id
  manyToOne:
    account:
      targetEntity:  App\Entity\ClientAccount
      inversedBy: accountOutsideFunds
      cascade: ['persist']
    securityAssignment:
      targetEntity:  App\Entity\SecurityAssignment
      inversedBy: accountAssociations
      joinColumn:
        name: security_assignment_id
        referencedColumnName: id
      cascade: ['persist']
  lifecycleCallbacks: {  }