App\Entity\AccountType:
  type: entity
  table: client_account_types
  repositoryClass: App\Repository\AccountTypeRepository
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    name:
      type: string(255)
      nullable: false
  oneToMany:
    groupTypes:
      targetEntity:  App\Entity\AccountGroupType
      mappedBy: type
      cascade: ['persist']
  lifecycleCallbacks: {  }