App\Entity\Bill:
    type: entity
    table: bill
    repositoryClass: App\Repository\BillRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        quarter:
            type: integer
            nullable: true
        year:
            type: integer
            nullable: true
        approvedAt:
            type: datetime
            nullable: true
        createdAt:
            type: datetime
            gedmo:
                timestampable:
                    on: create
    oneToMany:
        billItems:
            targetEntity:  App\Entity\BillItem
            mappedBy: bill
            cascade: ['persist']
    manyToOne:
        client:
            targetEntity:  App\Entity\User
            joinColumn:
                name: client_id
                referencedColumnName: id
                onDelete: cascade
            inversedBy: bills