App\Entity\ClientSettings:
    type: entity
    table: client_settings
    repositoryClass: App\Repository\ClientSettings
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        client_id:
            type: integer
            nullable: false
        stop_tlh_value:
            type: float
            nullable: true
        client_type:
            type: string(10)
            nullable: false
    oneToOne:
        client:
            targetEntity:  App\Entity\User
            inversedBy: clientSettings
            joinColumn:
                name: client_id
                referencedColumnName: id
                onDelete: cascade
            cascade: ['persist']