App\Entity\ClientAccountOwner:
    type: entity
    table: client_account_owners
    repositoryClass: App\Repository\ClientAccountOwnerRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        account_id:
            type: integer
            nullable: true
        owner_contact_id:
            type: integer
            nullable: true
        owner_client_id:
            type: integer
            nullable: true
        owner_type:
            type: string(10)
            nullable: false
    manyToOne:
        account:
            targetEntity:  App\Entity\ClientAccount
            inversedBy: accountOwners
            joinColumn:
                name: account_id
                referencedColumnName: id
                onDelete: cascade
        contact:
            targetEntity:  App\Entity\ClientAdditionalContact
            joinColumn:
                name: owner_contact_id
                referencedColumnName: id
                onDelete: cascade
            cascade: ['persist']
        client:
            targetEntity:  App\Entity\User
            joinColumn:
                name: owner_client_id
                referencedColumnName: id
                onDelete: cascade