App\Entity\ClientActivitySummary:
    type: entity
    table: client_activity_summaries
    repositoryClass: App\Repository\ClientActivitySummaryRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        client_id:
            type: integer
            nullable: false
        description:
            type: string(255)
            nullable: false
        is_show_ria:
            type: boolean
            nullable: true
        document_id:
            type: integer
            nullable: true
        created:
          type: datetime
          gedmo:
            timestampable:
              on: create
    oneToOne:
        Document:
            targetEntity:  App\Entity\Document
            joinColumn:
                name: document_id
                referencedColumnName: id
                onDelete: cascade
            cascade: ['persist']
    manyToOne:
        client:
            targetEntity:  App\Entity\User
            inversedBy: clientActivitySummaries
            joinColumn:
                name: client_id
                referencedColumnName: id
                onDelete: cascade
            cascade: ['persist']
    lifecycleCallbacks: {  }