App\Entity\ClientPortfolio:
  type: entity
  table: client_portfolio
  repositoryClass: App\Repository\ClientPortfolioRepository
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    client_id:
      type: integer
      nullable: false
    portfolio_id:
      type: integer
      nullable: false
    status:
      type: string
      length: 20
      nullable: false
    is_active:
      type: boolean
      nullable: true
    approved_at:
      type: date
      nullable: true
    accepted_at:
      type: date
      nullable: true
    created_at:
      type: date
      gedmo:
        timestampable:
          on: create
  manyToOne:
    client:
      targetEntity:  App\Entity\User
      inversedBy: clientPortfolios
      joinColumn:
        name: client_id
        referencedColumnName: id
        onDelete: cascade
      cascade: ['persist']
    portfolio:
      targetEntity:  App\Entity\CeModel
      inversedBy: clientPortfolio
      joinColumn:
        name: portfolio_id
        referencedColumnName: id
        onDelete: cascade
      cascade: ['persist']