App\Entity\RiskAnswer:
    type: entity
    repositoryClass: App\Repository\RiskAnswerRepository
    table: risk_answers
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        risk_question_id:
            type: integer
        title:
            type: string
            length: 255
        point:
            type: integer
    manyToOne:
        question:
            targetEntity:  App\Entity\RiskQuestion
            inversedBy: answers
            joinColumn:
                name: risk_question_id
                referencedColumnName: id
                onDelete: cascade
            cascade: ['persist']
    lifecycleCallbacks: {  }
