App\Entity\State:
  type: entity
  table: states
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    name:
      type: string(255)
      nullable: false
    abbr:
      type: string(4)
      nullable: false
  lifecycleCallbacks: {  }