App\Entity\Subclass:
  type: entity
  table: subclasses
  repositoryClass: App\Repository\SubclassRepository
  uniqueConstraints:
    unique_subclass_idx:
      columns: [ asset_class_id, name ]
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    asset_class_id:
      type: integer
      nullable: false
    owner_id:
      type: integer
      nullable: true
    source_id:
      type: integer
      nullable: true
    name:
      type: string(255)
      nullable: false
    expected_performance:
      type: float
      nullable: false
    account_type_id:
      type: integer
      nullable: true
    priority:
      type: integer
      nullable: true
    tolerance_band:
      type: integer
      nullable: true
  manyToOne:
    assetClass:
      targetEntity:  App\Entity\AssetClass
      inversedBy:   subclasses
      joinColumn:
        name: asset_class_id
        referencedColumnName: id
        onDelete: cascade
      cascade: ['persist']
    accountType:
      targetEntity:  App\Entity\SubclassAccountType
      joinColumn:
          name: account_type_id
          referencedColumnName: id
          onDelete: cascade
      cascade: ['persist']
    owner:
      targetEntity:  App\Entity\User
      joinColumn:
        name: owner_id
        referencedColumn: id
        onDelete: cascade
      cascade: ['persist']
    source:
      targetEntity:  App\Entity\Subclass
      inversedBy: targets
      joinColumn:
        name: source_id
        referencedColumn: id
        onDelete: cascade
      cascade: ['persist']
  oneToMany:
    targets:
      targetEntity:  App\Entity\Subclass
      mappedBy: source
    securityAssignments:
      targetEntity:  App\Entity\SecurityAssignment
      mappedBy: subclass
      cascade: ['persist']
    ceModelEntities:
      targetEntity:  App\Entity\CeModelEntity
      mappedBy: subclass
  lifecycleCallbacks: {  }