App\Entity\TransactionType:
    type: entity
    table: transaction_types
    repositoryClass: App\Repository\TransactionTypeRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        name:
            type: string
            length: 45
            nullable: true
        activity:
            type: string
            length: 45
            nullable: true
        report_as:
            type: string
            length: 45
            nullable: true
        description:
            type: string
            length: 255
            nullable: true