App\Entity\TransactionFeeType:
    type: entity
    table: transaction_fee_types
    repositoryClass: App\Repository\TransactionFeeTypeRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        name:
            type: string
            length: 45
            nullable: true
        description:
            type: string
            length: 45
            nullable: true